version: '3.8'

services:
  flask_app:
    image: shirishkrishna/movie-recommender:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=YourSecurePassword
    depends_on:
      - prometheus
    restart: always

networks:
  monitoring:
    driver: bridge